---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apiservice-healer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apiservice-healer
subjects:
- kind: ServiceAccount
  name: apiservice-healer
  namespace: kube-system
